name: Format Python code
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  Autoyapf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Auto yapf
        uses: AlexanderMelde/yapf-action@master
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@main
        with:
          commit-message: Automated code formatting.
          committer: AnonymousR1025 <102808014+AnonymousR1025@users.noreply.github.com>
          title: Automated code formatting.
          body: This is an automated code formatting pull request.
          labels: Code Formatting
          reviewers: AnonymousR1025
          branch: autofixes
